#166240980 Integrate TravisCI with readme badge
andela/tesla-ah pull request #1
Opened 2019-06-03 12:12 UTC by EmyRukundo

**What does this PR do?**

   Integrate TravisCI with readme badge

 **Description of Task to be completed?**

  this is for running the test and respond 
with the status, if it is passing  or failing  

**What are the relevant pivotal tracker stories?**

#166240980

2019-06-03 14:23 UTC, deschantkn commented on README.md
>  Authors Haven - A Social platform for the creative at heart.
```suggestion
Authors Haven - A Social platform for the creative at heart
```

2019-06-03 14:28 UTC, Diama1 approved these changes

2019-06-03 14:29 UTC, mifeille approved these changes

2019-06-03 14:31 UTC, deschantkn approved these changes

2019-06-03 15:42 UTC, Quantum-35 requested changes
@EmyRukundo Kindly Squash your commits to one.

2019-06-03 15:53 UTC, eliemugenzi approved these changes

2019-06-03 15:59 UTC, rukundoeric commented
Your test script is duplicated and it can't support es6 features

2019-06-03 16:02 UTC, rukundoeric requested changes
Your test script is duplicated and it can't support es6 features

2019-06-05 07:32 UTC, EmyRukundo commented
> @EmyRukundo Kindly Squash your commits to one.

>@Quantum-35 yes, I did

2019-06-05 07:42 UTC, rukundoeric approved these changes

2019-06-05 11:44 UTC, Quantum-35 commented
Please fix the merge conflicts

2019-06-05 12:37 UTC, EmyRukundo commented
> Please fix the merge conflicts

It's fixed now

2019-06-05 14:09 UTC, Quantum-35 requested changes

2019-06-05 14:09 UTC, Quantum-35 commented on README.md
> +[![Build Status](https://travis-ci.com/andela/tesla-ah.svg?branch=master)](https://travis-ci.com/andela/tesla-ah)
Change this Link to point to Develop for correct readings.

2019-06-05 14:36 UTC, Quantum-35 commented
Kindly Rebase and delete `package-lock.json` and `node_modules`. Then run yarn install.

2019-06-05 17:36 UTC, Quantum-35 approved these changes

2019-06-05 17:37 UTC, merged