#166240991 Add user registration validation errors
andela/tesla-ah pull request #18
Opened 2019-06-11 12:30 UTC by mifeille

### What does this PR do?

Add registration validation errors when a user enters invalid user parameters like:
• existing user email
• invalid email
• password of length less than 8
• password not being alphanumeric

### Description of Task to be completed?
• write unit tests
• come up with the Algorithm needed to implement the feature

### How should this be manually tested?

Clone the  repo, cd into it and RUN ` yarn install ` to install all the dependencies,
RUN ` yarn test ` for tests,
then RUN ` yarn dev ` to start the server.
- use postman and use ` POST /api/auth/signup ` endpoint to test if the validations are working.

Sample request body to signup
  ```
 {
	"firstName": "Mireille",
	"username": "mifeille",
	"lastName": "Niwemuhuza",
	"email": "nimilleer@gmail.com",
	"password": "mireille1!",
	"confirmPassword": "mireille1!",
	"gender":"F"
}
```

### What are the relevant pivotal tracker stories?

#166240991

2019-06-11 12:40 UTC, deschantkn requested changes

2019-06-11 12:40 UTC, deschantkn commented on src/index.js
> +app.use('/', swaggerUi.serve, swaggerUi.setup(swaggerDoc));
You should use `app.get` instead of `app.use`

2019-06-11 12:50 UTC, deschantkn approved these changes

2019-06-11 13:44 UTC, eliemugenzi approved these changes

2019-06-11 13:47 UTC, EmyRukundo approved these changes

2019-06-12 11:57 UTC, Quantum-35 requested changes

2019-06-12 11:57 UTC, Quantum-35 commented on src/helpers/signupSchema.js
> +        .required()
Good initiative creating this `SignupSchema` validation file. But I suggest you create another file whereby all validations that are clients of reusability like email and password validation be added there then its children can reuse those validations.

2019-06-12 11:57 UTC, Quantum-35 commented on src/middleware/userExists.js
> +    const { email } = req.body;
You can create several functions that validate user existence and other validations like body and export them instead of creating several files.

2019-06-12 12:19 UTC, Quantum-35 requested changes
I have just noticed that the error message of a single missing field is being displayed thrice. Can you fix that?

<img width="1129" alt="Screenshot 2019-06-12 at 15 16 34" src="https://user-images.githubusercontent.com/39088834/59350593-2bd20000-8d25-11e9-93c4-ee8ee7ba9693.png">

2019-06-12 20:13 UTC, Quantum-35 approved these changes

2019-06-13 05:56 UTC, Quantum-35 approved these changes

2019-06-13 05:56 UTC, merged