#166240995 User profile creation
andela/tesla-ah pull request #19
Opened 2019-06-12 13:35 UTC by deschantkn

#### What does this PR do?
Enables user to create and update their profile information

#### Description of Task to be completed?
Implement the following endpoints:
- `PUT - /api/user`
- `GET - /profiles/:username`

#### How should this be manually tested?
Run the server and use Postman to test

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
#166240995

#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

2019-06-12 15:45 UTC, rukundoeric approved these changes

2019-06-13 06:00 UTC, Quantum-35 commented
@deschantkn Fix the Merge conflicts

2019-06-13 08:46 UTC, Quantum-35 requested changes

2019-06-13 08:46 UTC, Quantum-35 commented on package.json
> +    "@babel/polyfill": "^7.4.4",
This package has been deprecated as of babel 7.

2019-06-13 08:46 UTC, Quantum-35 commented on src/api/controllers/profiles.js
> +import models from '../../sequelize/models';
I don't find any valid reason for creating two files `pofiles.js` and `users.js`. You can just move all the implementation in the `user.js` to ProfileController class to make it more readable. 
Anything to say about this suggestion?

2019-06-13 09:04 UTC, deschantkn commented on src/api/controllers/profiles.js
> +import models from '../../sequelize/models';
No I think this logic is more sound than what I currently have. Will make the necessary changes

2019-06-13 09:05 UTC, deschantkn commented on package.json
> +    "@babel/polyfill": "^7.4.4",
Okay, will look into it and make updates

2019-06-13 09:32 UTC, mifeille approved these changes

2019-06-13 10:25 UTC, Diama1 approved these changes

2019-06-13 14:59 UTC, Quantum-35 approved these changes

2019-06-13 17:21 UTC, merged