#166240992 User SignOut
andela/tesla-ah pull request #22
Opened 2019-06-12 16:10 UTC by Diama1

#### What does this PR do?
Enables user to sign out from the system. 

#### Description of Task to be completed?
Implement the following endpoints:
- `POST - /api/login`
- `GET - /api/:signout`

#### How should this be manually tested?
Run the server and use Postman to test

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
#166240992

#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

2019-06-13 18:00 UTC, Quantum-35 requested changes

2019-06-13 18:00 UTC, Quantum-35 commented on src/api/controllers/auth.js
> +        message: 'You are now signed in!',
Update db dropped message

2019-06-13 18:00 UTC, Quantum-35 commented on src/middleware/auth.js
> +      try {
I don't see the essence of having a nested try.

2019-06-14 07:56 UTC, Diama1 commented on src/middleware/auth.js
> +      try {
We are trying to catch database errors separately from token decoding errors and handle them separately.

2019-06-14 08:30 UTC, deschantkn requested changes

2019-06-14 08:30 UTC, deschantkn commented on src/index.js
> +app.get('/', swaggerUi.serve, swaggerUi.setup(swaggerDoc));
Use `app.use` and place the swagger router below all other routes.

2019-06-14 08:30 UTC, deschantkn commented on test/auth.js
> +import chaiHttp from 'chai-http';
I believe this file was renamed to `auth.test.js`. Could check if you don't already have it ? if you do then you can delete this file.

2019-06-14 09:18 UTC, Quantum-35 approved these changes

2019-06-14 09:32 UTC, merged

2019-06-14 09:36 UTC, EmyRukundo approved these changes