#166240992 Bug fixed for uncovered test.
andela/tesla-ah pull request #31
Opened 2019-06-17 10:47 UTC by Diama1

#### What does this PR do?
Fixes a bug for the uncovered tests.

#### Description of Task to be completed?
run tests by `yarn run test` to check the uncovered tests.
and then fixed them. 

#### How should this be manually tested?
N/A

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
N/A

#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

2019-06-17 15:41 UTC, eliemugenzi approved these changes

2019-06-17 15:41 UTC, eliemugenzi approved these changes

2019-06-17 15:42 UTC, eliemugenzi approved these changes

2019-06-17 15:43 UTC, eliemugenzi approved these changes

2019-06-17 15:49 UTC, deschantkn approved these changes

2019-06-17 16:00 UTC, mifeille approved these changes

2019-06-18 05:22 UTC, Quantum-35 requested changes
Travis CI branch is failing. Fix it.

2019-06-18 07:27 UTC, Quantum-35 approved these changes

2019-06-18 08:19 UTC, merged