#166241008:  feat(article): user should get article read time
andela/tesla-ah pull request #35
Opened 2019-06-17 13:09 UTC by eliemugenzi

https://docs.google.com/document/d/1L9nIyaff15pa2zggxFo-ywBYjqUwNDlBGhEEOff43C8/edit?usp=sharing

2019-06-17 15:43 UTC, Diama1 approved these changes

2019-06-17 15:43 UTC, Diama1 approved these changes

2019-06-17 15:53 UTC, mifeille approved these changes

2019-06-17 16:17 UTC, rukundoeric approved these changes

2019-06-18 05:38 UTC, Quantum-35 requested changes
LGTM

2019-06-18 05:39 UTC, Quantum-35 approved these changes

2019-06-18 05:39 UTC, merged