#166240997 User is able to create ratings on Article.
andela/tesla-ah pull request #39
Opened 2019-06-18 08:07 UTC by Diama1

#### What does this PR do?
Enables user to create a rating on the article.
#### Description of Task to be completed?
- run the migration `sequelize db:migrate`

- install the packages `yarn install`

- run the server `yarn dev`

#### How should this be manually tested?
N/A

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
166240997
#### Screenshots (if appropriate)
N/A

#### Questions:
N/A
#### Use Case Documentation #166240997
https://docs.google.com/document/d/18hLJGa1CoRrNm3wpl0bEP6vwslUVV0PvqBUb5ZfqkmQ/edit

2019-06-19 06:00 UTC, deschantkn approved these changes

2019-06-19 14:16 UTC, eliemugenzi approved these changes

2019-06-19 14:45 UTC, deschantkn commented on src/helpers/validationSchemas.js
> +  Rating: Joi.object().keys({
This validation schema will not work.  Just keep this: 
```javascript
rating: Joi.number()
      .integer()
      .positive()
      .min(1)
      .max(5)
      .required()
      .label('Rating must be from 1 to 5 ')
  })
```

No need to wrap it in `Joi.obect().keys({...`

2019-06-19 15:03 UTC, deschantkn approved these changes

2019-06-20 10:39 UTC, rukundoeric approved these changes

2019-06-21 08:05 UTC, Quantum-35 requested changes

2019-06-21 08:05 UTC, Quantum-35 commented on src/api/controllers/ratingController.js
> +    // else {
Remove this commented out code.

2019-06-21 09:10 UTC, Quantum-35 approved these changes

2019-06-21 15:54 UTC, merged