#166740799 User can upload images
andela/tesla-ah pull request #44
Opened 2019-06-20 09:50 UTC by deschantkn

#### What does this PR do?
This PR creates enables file upload using  `multer` and `Cloudinary` as CDN service for images.

#### Description of Task to be completed?
- create multer handler
- create cloudinary configuration

#### How should this be manually tested?
This can be tested by uploading an image on the signup endpoint in Postman 

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
#166740799

#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

#### Use Case documentation
https://docs.google.com/document/d/1bAgtj078tIU55pGEvO4A8-cL8I2F5w8_zvAaRtlY5sE/edit?usp=sharing

2019-06-20 10:28 UTC, Diama1 approved these changes

2019-06-20 10:48 UTC, rukundoeric requested changes

2019-06-20 10:48 UTC, rukundoeric commented on src/helpers/uploadHelper.js
> +  }
could you check the error status first, just like this.   ```res.status(error.status || 500)```

2019-06-20 15:06 UTC, rukundoeric approved these changes

2019-06-20 15:09 UTC, mifeille approved these changes

2019-06-21 15:28 UTC, Quantum-35 approved these changes

2019-06-21 15:28 UTC, merged