feat(report-article): Enable user to report an article
andela/tesla-ah pull request #52
Opened 2019-06-24 12:49 UTC by rukundoeric

### What does this PR do?
*   Enable user to report an article
### Description of Task to be completed?
  Have this endpoint working
 * `POST /api/articles/report/:slug`
### How should this be manually tested?
 * pull this branch
 * Add some records in your Users table in the database.
 * And the test that API above with postman
### Any background context you want to provide?

N/A

### What are the relevant pivotal tracker stories?

[#166241011](https://www.pivotaltracker.com/story/show/166241011)

### Use case documentation
[Report an article user case documentaion](https://docs.google.com/document/d/1TW7iS_gFzGbtmZVlV921vOT-LgRrMTuzupH_04SIqx0/edit?usp=sharing)
### Screenshots (if appropriate)
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/45217364/60019856-219df300-968f-11e9-8327-2b6be1b2791e.gif)

### Questions:
N/A

2019-06-24 13:46 UTC, eliemugenzi requested changes

2019-06-24 13:46 UTC, eliemugenzi commented on src/api/routes/articlesRouter.js
> +articlesRouter.post('/report/:slug', verifyToken, validateBody('checkComment'), slugExist, reportArticle);
Please consider the order of this route order `/api/articles/:slug/report` I think it should look better and easier when we'll be on front-end side.

2019-06-25 10:53 UTC, eliemugenzi approved these changes

2019-06-25 11:34 UTC, UhiriweAudace approved these changes

2019-06-25 15:26 UTC, deschantkn approved these changes

2019-06-26 12:35 UTC, Quantum-35 requested changes

2019-06-26 12:35 UTC, Quantum-35 commented on .env.example
> +>>>>>>> feat(report-article): Enable user to report an article
Check out this file.

2019-06-26 12:35 UTC, Quantum-35 commented on package.json
> +    "express-openapi-validator": "^1.0.0",
Remove unused package.

2019-06-27 08:16 UTC, Quantum-35 approved these changes

2019-06-27 08:21 UTC, merged