ft-sharing-articles-on-different-channels-166241009
andela/tesla-ah pull request #56
Opened 2019-06-26 09:03 UTC by EmyRukundo

**What does this PR do?**

sharing articles on different channels

**Description of Task to be completed?**

As an authenticated user, I should be able to share articles; both mine and others via email and social media platforms.
link for use case:https://docs.google.com/document/d/1NfrEF7icPY-lxrrTDL_c67buOxs61qxAxPJoTKQvnio/edit?usp=sharing

**How should this be manually tested?**
learn test by yarn test: reset

**Any background context you want to provide?**

N/A

**What are the relevant pivotal tracker stories?**

#166241009

**Screenshots (if appropriate)**

N/A

**Questions:**

N/A

2019-06-26 10:46 UTC, deschantkn approved these changes

2019-06-26 10:48 UTC, eliemugenzi approved these changes

2019-06-26 11:32 UTC, rukundoeric approved these changes

2019-06-27 18:38 UTC, Quantum-35 requested changes

2019-06-27 18:38 UTC, Quantum-35 commented on src/middleware/checkUsernameExist.js
> +    // console.log(user);
Remove the console.logs in line 6 and 12.

2019-06-27 18:43 UTC, Quantum-35 approved these changes

2019-07-01 09:57 UTC, merged