#167129854 Fetch all blocked articles
andela/tesla-ah pull request #71
Opened 2019-07-09 09:46 UTC by deschantkn

#### What does this PR do?
Admin or moderator can fetch blocked articles

#### Description of Task to be completed?
Have the following endpoint working:
- `GET - /api/articles/blocked/all`

#### How should this be manually tested?
This PR can be tested using Postman after checking into this branch

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
#167129854

#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

2019-07-10 09:55 UTC, eliemugenzi requested changes

2019-07-10 09:55 UTC, eliemugenzi commented on src/api/controllers/articlesController.js
> +    return res.status(200).json({ status: 200, data: blockedArticles || [] });
It returns an empty array by default, in case there is no blocked article.

2019-07-10 09:55 UTC, eliemugenzi commented on src/api/controllers/articlesController.js
> +    return res.status(200).json({ status: 200, data: reportedArticles || [] });
The same here.

2019-07-11 10:41 UTC, mifeille approved these changes

2019-07-11 13:28 UTC, Quantum-35 approved these changes
LGTM

2019-07-11 13:28 UTC, merged